server {
    listen 80;
    server_name pariconnect.local;

    location /api/ {
        proxy_pass http://api:4000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://admin:3000/;
    }

    location / {
        proxy_pass http://web:3000/;
    }
}
